apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
#  googleCloudBuild:
#    projectId: ticketing-306309
  artifacts:
    - image: jawulya/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jawulya/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: jawulya/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jawulya/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jawulya/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jawulya/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

#k create secret generic jwt-secret --from-literal=JWT_KEY=asdf
#k create secret generic stripe-secret --from-literal=STRIPE_KEY=sk_test_51IkqfKHEr0dxCxHcFL3Bot21xRbM7Jzee23QJvaH9aJGWb46C84mtxdibtDzBfkvZ6OoHSvzVDLMo4l9bBAAyb0C00uhAa8vuY
#ingress kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.45.0/deploy/static/provider/cloud/deploy.yaml
